<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\thumbnails\" />
    <Folder Include="wwwroot\uploads\photos\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\PhotoGallery.ServiceDefaults\PhotoGallery.ServiceDefaults.csproj" />
    <ProjectReference Include="..\PhotoGallery.Application\PhotoGallery.Application.csproj" />
    <ProjectReference Include="..\PhotoGallery.Infrastructure\PhotoGallery.Infrastructure.csproj" />
  </ItemGroup>

</Project>
